# Generated by Django 3.0.6 on 2020-06-11 11:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('key', models.SlugField(editable=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('imageUrl', models.ImageField(upload_to='%d-%m-%Y/images', verbose_name='image')),
            ],
        ),
    ]
