# Generated by Django 3.0.6 on 2020-06-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='key',
            field=models.SlugField(editable=False, verbose_name='slug'),
        ),
    ]
